//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Blog</summary>
	[PublishedContentModel("blogContent")]
	public partial class BlogContent : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Blog: Blog Page Title
		///</summary>
		[ImplementPropertyType("blog")]
		public string Blog
		{
			get { return this.GetPropertyValue<string>("blog"); }
		}

		///<summary>
		/// Blog Header Image
		///</summary>
		[ImplementPropertyType("blogHeaderImage")]
		public string BlogHeaderImage
		{
			get { return this.GetPropertyValue<string>("blogHeaderImage"); }
		}

		///<summary>
		/// Blog Page Description
		///</summary>
		[ImplementPropertyType("blogPageDescription")]
		public IHtmlString BlogPageDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("blogPageDescription"); }
		}
	}
}
