//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home Page</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Description
		///</summary>
		[ImplementPropertyType("headerDescription")]
		public IHtmlString HeaderDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("headerDescription"); }
		}

		///<summary>
		/// Prices Description
		///</summary>
		[ImplementPropertyType("pricesDescription")]
		public IHtmlString PricesDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("pricesDescription"); }
		}

		///<summary>
		/// Price Title
		///</summary>
		[ImplementPropertyType("priceTitle")]
		public string PriceTitle
		{
			get { return this.GetPropertyValue<string>("priceTitle"); }
		}

		///<summary>
		/// Programs Description
		///</summary>
		[ImplementPropertyType("programsDescription")]
		public IHtmlString ProgramsDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("programsDescription"); }
		}

		///<summary>
		/// Programs Title
		///</summary>
		[ImplementPropertyType("programsTitle")]
		public string ProgramsTitle
		{
			get { return this.GetPropertyValue<string>("programsTitle"); }
		}

		///<summary>
		/// Trainers Description
		///</summary>
		[ImplementPropertyType("trainersDescription")]
		public IHtmlString TrainersDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("trainersDescription"); }
		}

		///<summary>
		/// Trainers Title
		///</summary>
		[ImplementPropertyType("trainersTitle")]
		public string TrainersTitle
		{
			get { return this.GetPropertyValue<string>("trainersTitle"); }
		}

		///<summary>
		/// Website Title
		///</summary>
		[ImplementPropertyType("websiteTitle")]
		public string WebsiteTitle
		{
			get { return this.GetPropertyValue<string>("websiteTitle"); }
		}
	}
}
