//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Tariff</summary>
	[PublishedContentModel("price")]
	public partial class Price : Prices
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "price";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Price(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Price, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Best Value
		///</summary>
		[ImplementPropertyType("bestValue")]
		public bool BestValue
		{
			get { return this.GetPropertyValue<bool>("bestValue"); }
		}

		///<summary>
		/// Tariff Description
		///</summary>
		[ImplementPropertyType("tariffDescription")]
		public IHtmlString TariffDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("tariffDescription"); }
		}

		///<summary>
		/// Tariff Length
		///</summary>
		[ImplementPropertyType("tariffLength")]
		public string TariffLength
		{
			get { return this.GetPropertyValue<string>("tariffLength"); }
		}

		///<summary>
		/// Tariff Price
		///</summary>
		[ImplementPropertyType("tariffPrice")]
		public string TariffPrice
		{
			get { return this.GetPropertyValue<string>("tariffPrice"); }
		}

		///<summary>
		/// Tariff Type
		///</summary>
		[ImplementPropertyType("tariffType")]
		public string TariffType
		{
			get { return this.GetPropertyValue<string>("tariffType"); }
		}
	}
}
