//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Program</summary>
	[PublishedContentModel("program")]
	public partial class Program : Programs
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "program";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Program(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Program, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Program Description
		///</summary>
		[ImplementPropertyType("programDescription")]
		public IHtmlString ProgramDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("programDescription"); }
		}

		///<summary>
		/// Program Icon
		///</summary>
		[ImplementPropertyType("programIcon")]
		public string ProgramIcon
		{
			get { return this.GetPropertyValue<string>("programIcon"); }
		}

		///<summary>
		/// Program Title
		///</summary>
		[ImplementPropertyType("programTitle")]
		public string ProgramTitle
		{
			get { return this.GetPropertyValue<string>("programTitle"); }
		}
	}
}
