//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Trainer</summary>
	[PublishedContentModel("trainer")]
	public partial class Trainer : Trainers
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "trainer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Trainer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Trainer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Trainer Description
		///</summary>
		[ImplementPropertyType("trainerDescription")]
		public IHtmlString TrainerDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("trainerDescription"); }
		}

		///<summary>
		/// Trainer Facebook
		///</summary>
		[ImplementPropertyType("trainerFacebook")]
		public string TrainerFacebook
		{
			get { return this.GetPropertyValue<string>("trainerFacebook"); }
		}

		///<summary>
		/// Trainer Image
		///</summary>
		[ImplementPropertyType("trainerImage")]
		public string TrainerImage
		{
			get { return this.GetPropertyValue<string>("trainerImage"); }
		}

		///<summary>
		/// Trainer Instagram
		///</summary>
		[ImplementPropertyType("trainerInstagram")]
		public string TrainerInstagram
		{
			get { return this.GetPropertyValue<string>("trainerInstagram"); }
		}

		///<summary>
		/// Trainer Name
		///</summary>
		[ImplementPropertyType("trainerName")]
		public string TrainerName
		{
			get { return this.GetPropertyValue<string>("trainerName"); }
		}

		///<summary>
		/// Trainer Title
		///</summary>
		[ImplementPropertyType("trainerTitle")]
		public string TrainerTitle
		{
			get { return this.GetPropertyValue<string>("trainerTitle"); }
		}
	}
}
